//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyPerformanceReportAuto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DailyQuote
    {
        public int Id { get; set; }
        public string QuoteSource { get; set; }
        public string QuoteType { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime Date { get; set; }
        public string Value { get; set; }
        public string Comments { get; set; }
    }
}
