//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyPerformanceReportAuto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DailyPerformanceReportDbEntities1 : DbContext
    {
        public DailyPerformanceReportDbEntities1()
            : base("name=DailyPerformanceReportDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DailyQuote> DailyQuotes { get; set; }
    
        public virtual ObjectResult<Nullable<int>> GetEntryDates(string quoteSource)
        {
            var quoteSourceParameter = quoteSource != null ?
                new ObjectParameter("QuoteSource", quoteSource) :
                new ObjectParameter("QuoteSource", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetEntryDates", quoteSourceParameter);
        }
    }
}
